export const DINEROS_REQUEST = "DINEROS_REQUEST";
export const DINEROS_REQUEST_SUCCESS = "DINEROS_REQUEST_SUCCESS";
export const DINEROS_REQUEST_FAIL = "DINEROS_REQUEST_FAIL";

export const UPDATE_DINEROS_REQUEST = "UPDATE_DINEROS_REQUEST";
export const UPDATE_DINEROS_REQUEST_SUCCESS = "UPDATE_DINEROS_REQUEST_SUCCESS";
export const UPDATE_DINEROS_REQUEST_FAIL = "UPDATE_DINEROS_REQUEST_FAIL";
