export const MOVEMENT_REQUEST = "MOVEMENT_REQUEST";
export const MOVEMENT_REQUEST_SUCCESS = "MOVEMENT_REQUEST_SUCCESS";
export const MOVEMENT_REQUEST_FAIL = "MOVEMENT_REQUEST_FAIL";

export const GET_MOVEMENT_REQUEST = "GET_MOVEMENT_REQUEST";
export const GET_MOVEMENT_REQUEST_SUCCESS = "GET_MOVEMENT_REQUEST_SUCCESS";
export const GET_MOVEMENT_REQUEST_FAIL = "GET_MOVEMENT_REQUEST_FAIL";

export const GET_DETAIL = "GET_DETAIL";
export const GET_DETAIL_SUCCESS = "GET_DETAIL_SUCCESS";
export const GET_DETAIL_FAIL = "GET_DETAIL_FAIL";
